# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'liwushuo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!  SDWebImage MBProgressHUD
pod 'AFNetworking'
pod 'KVNProgress'
pod 'Masonry'
pod 'FMDB'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'MBProgressHUD'

  # Pods for liwushuo

  target 'liwushuoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'liwushuoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
